# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Starter-Smart
version:      v0.0.2
version_from: lib/Module/Starter/Smart.pm
installdirs:  site
requires:
    ExtUtils::Command:             0
    File::Spec:                    0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
